meta_product_name: "Le Plateau"
meta_title: "Le plateau - Trouve ton jeu de société, tes buddies ou les deux !"
meta_description: "Vous disposez d'un jeu de société mais pas assez de joueurs pour vous accompagner ? Vous avez l'âme d'un joueur mais ni jeu ni copain pour passer du bon temps ? Le Plateau est là pour vous ! Rejoignez sans plus tarder un évènement à venir ! Vous pourrez rencontrer de nouvelles personnes et jouer sans modération."
meta_image: "leplateau.png"
